// MobileKeysInternalErrorCodes.h
// Copyright (c) 2016 ASSA ABLOY Mobile Services ( http://assaabloy.com/seos )
//
// All rights reserved.

/**
 * The domain used for all NSError objects originating from Mobile Keys.
 */
extern NSString *MobileKeysErrorDomain;
extern NSString *MobileKeysHttpErrorDomain;

/**
 * \enum MobileKeysErrorCode
 * NSError objects generated by MobileKeys will contain one of these codes.
 * Please look at the individual codes to see what they mean. The codes ending
 * in RetryError indicates that a retry can be attempted.
 *
 * @note since version 2.0
 */
typedef NS_ENUM(NSInteger, MobileKeysInternalErrorCode) {
    /**
     * 1, Unknown error
     */
    MobileKeysInternalErrorCodeUnknown = 1,
    /**
     * 99, Failed to connect to the secure element
     */
    MobileKeysInternalErrorCodeInternal = 99,
    /**
     * 100 There was a general error communicating with the secure storage
     */
    MobileKeysInternalErrorCodeSecureElement = 100,
    /**
     * 106, Error while processing server package (FATAL)
     */
    MobileKeysInternalErrorCodeEndpoint = 106,
    /**
     * 107, Endpoint not setup
     */
    MobileKeysInternalErrorCodeEndpointNotSetup = 107,
    /**
     * 202, Data storage decryption failed
     */
    MobileKeysInternalErrorCodeDataStorageDecryptionFailed = 202,
    /**
     * 203, Data storage encryption failed
     */
    MobileKeysInternalErrorCodeDataStorageEncryptionFailed = 203,
    /**
     * 204, Data storage was corrupted and could not be recovered
     */
    MobileKeysInternalErrorCodeDataStorageCorrupted = 204,
    /**
     * 300, Failed to communicate with the Mobile Keys Platform
     */
    MobileKeysInternalErrorCodeServerCommunicationFailed = 300,
    /**
     *  307, Could not reach internet (íOS Only). Recommended user action is to fix permissions or network access
     */
    MobileKeysInternalErrorCodeNetworkUnreachable = 307,
    /**
     * 401, One asynchrounous method of the API is already running
     */
    MobileKeysInternalErrorCodeSDKBusy = 401,
    /**
     * 700, TSM replied NOT ELIGIBLE (FATAL during Setup, Invitation code no longer useful)
     */
    MobileKeysInternalErrorCodeDeviceNotEligible = 700,
    /**
     * 701, Server replied API INCOMPATIBLE (Upgrade app)
     */
    MobileKeysInternalErrorCodeSDKIncompatible = 701,
    /**
     * 702, The Endpoint registration failed. This is normally because of a network problem.
     */
    MobileKeysInternalErrorCodeDeviceSetupFailedRetry = 702,
    /**
     * 703, The TSM failed to install the Applet with a fatal error (FATAL, Invitation code no longer useful)
     */
    MobileKeysInternalErrorCodeDeviceSetupFailed = 703,
    /**
     * 901 The TSM Reported that the invitation code was not valid (FATAL, Invitation code not valid)
     */
    MobileKeysInternalErrorCodeInvalidInvitationCode = 901,
    /**
     * 902 The TSM Reported that this invitation code is not valid for this application (FATAL, Invitation code not valid)
     */
    MobileKeysInternalErrorCodeInvalidApplication = 902,
   /**
     * 1101   MobileKeysManager was unable to serve the request to open the specified reader since the request contained
     *        an OpeningType that was not in the list of permitted OpeningTypes. Recommended user action is to reconfigure reader.
     */
    MobileKeysInternalErrorCodeOpeningTypeNotPermitted = 1101,
    /**
     * 1103  MobileKeysManager were unable to serve the request since Bluetooth Low Energy is unavailable. Recommended user action is to fix permissions.
     */
    MobileKeysInternalErrorCodeBluetoothLENotAvailable = 1103,
};
