#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef SEOSMOBILEKEYSSDK_SWIFT_H
#define SEOSMOBILEKEYSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#import <SeosMobileKeysSDK/SeosMobileKeysSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SeosMobileKeysSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(uint8_t, CertificateType, open) {
  CertificateTypeCvc = 0x00,
  CertificateTypeX509 = 0x01,
};

enum State : NSInteger;
@protocol LegacyStateMachineDelegateProtocol;
enum ReaderModuleType : NSInteger;
@class NSString;

SWIFT_CLASS("_TtC17SeosMobileKeysSDK23LegacyReaderModuleState")
@interface LegacyReaderModuleState : NSObject
@property (nonatomic) enum State state;
- (nonnull instancetype)initWithDelegate:(id <LegacyStateMachineDelegateProtocol> _Nonnull)delegate initialState:(enum State)initialState readerModuleType:(enum ReaderModuleType)readerModuleType OBJC_DESIGNATED_INITIALIZER;
- (BOOL)allowTransitionTo:(enum State)to from:(enum State)from SWIFT_WARN_UNUSED_RESULT;
- (void)didTransitionTo:(enum State)to from:(enum State)from;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)textWithState:(enum State)state SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP17SeosMobileKeysSDK34LegacyStateMachineDelegateProtocol_")
@protocol LegacyStateMachineDelegateProtocol
- (void)didTransitionFromTo:(enum State)to from:(enum State)from;
@end

typedef SWIFT_ENUM(NSInteger, LogBleName, open) {
  LogBleNameBleConnect = 0,
  LogBleNameBleServiceDiscovery = 1,
  LogBleNameBleCharacteristicDiscovery = 2,
  LogBleNameBleDataTransfer = 3,
  LogBleNameBleIdle = 4,
  LogBleNameBleDisconnecting = 5,
  LogBleNameBleDisconnected = 6,
  LogBleNameBleConnecting = 7,
  LogBleNameBleAdvertising = 8,
  LogBleNameBleStarted = 9,
  LogBleNameBleDataReceived = 10,
  LogBleNameBleEndOfTransaction = 11,
  LogBleNameBleWaitForData = 12,
};

typedef SWIFT_ENUM(NSInteger, LogType, open) {
  LogTypeLogSeosCore = 0,
  LogTypeLogStatistics = 1,
  LogTypeLogBeacon = 2,
  LogTypeLogSeosApdus = 3,
  LogTypeLogSeosApi = 4,
  LogTypeLogSeosAccessApi = 5,
  LogTypeLogBleCommunication = 6,
  LogTypeLogBleConnection = 7,
  LogTypeLogLifecycle = 8,
  LogTypeLogKeyChain = 9,
  LogTypeLogNetwork = 10,
  LogTypeLogPersonalization = 11,
  LogTypeLogAPI = 12,
  LogTypeLogOpening = 13,
  LogTypeLogFileSystem = 14,
  LogTypeLogErrorHandler = 15,
  LogTypeLogReader = 16,
  LogTypeLogSeosSession = 17,
  LogTypeLogNfc = 18,
  LogTypeLogSecureChannelOpen = 19,
};


SWIFT_CLASS("_TtC17SeosMobileKeysSDK11LoggerSwift")
@interface LoggerSwift : NSObject
+ (void)removeFile;
+ (void)signPostBeginWithName:(enum LogBleName)name category:(enum LogType)category;
+ (void)signPostEndWithName:(enum LogBleName)name category:(enum LogType)category;
+ (void)logWithCategory:(enum LogType)category message:(NSString * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;

/// MobileKeysCryptoLib can be used to sign and to verify signatures using asymmetric keys
/// Algorithm ECDSA SHA256, with r | s = 64 bytes, (Not DER-encoded)
SWIFT_CLASS("_TtC17SeosMobileKeysSDK19MobileKeysCryptoLib")
@interface MobileKeysCryptoLib : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Init
/// @param keyPair - Data in the format “04” + Public key.x (32 bytes) + Public key.y (32 bytes) + Private key (32 bytes)
- (nonnull instancetype)initWithKeyPair:(NSData * _Nonnull)keyPair OBJC_DESIGNATED_INITIALIZER;
/// Get the signature size. The signature is  r | s and always 64 bytes
- (NSInteger)getSignatureSize SWIFT_WARN_UNUSED_RESULT;
/// Get the public key.
/// @return Returns the public key. Data in the format “04” + Public key.x (32 bytes) + Public key.y (32 bytes)
- (NSData * _Nullable)getPublicKey SWIFT_WARN_UNUSED_RESULT;
/// Verifies the message with the signature, using the public key.
/// <ul>
///   <li>
///     @param message - The message to verify the integrity of.
///   </li>
///   <li>
///     @param signature - Signature is  r | s and always 64 bytes of Data
///   </li>
///   <li>
///     @param publicKey - Data in the format “04” + Public key.x (32 bytes) + Public key.y (32 bytes) + Private key (32 bytes)
///   </li>
///   <li>
///     @return Returns true if verification is OK
///   </li>
/// </ul>
- (BOOL)verifyWithMessage:(NSData * _Nonnull)message signature:(NSData * _Nonnull)signature publicKey:(NSData * _Nonnull)publicKey SWIFT_WARN_UNUSED_RESULT;
/// Signes the message using the private key from the initialization of the MobileKeysCryptoLib.
/// <ul>
///   <li>
///     @param message - The message to sign
///   </li>
///   <li>
///     @return Returns the signature (r | s) and is always 64 bytes of Data
///   </li>
/// </ul>
- (NSData * _Nullable)signWithMessage:(NSData * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
@end

@class ReaderRepository;
@class MobileKeysReader;
@class TriggerResult;

SWIFT_CLASS("_TtC17SeosMobileKeysSDK24OpeningTriggerController")
@interface OpeningTriggerController : NSObject
- (nonnull instancetype)initWithRepository:(ReaderRepository * _Nonnull)repository OBJC_DESIGNATED_INITIALIZER;
- (TriggerResult * _Nonnull)rssiTriggerWithReader:(MobileKeysReader * _Nonnull)reader SWIFT_WARN_UNUSED_RESULT;
/// This trigger handles the case where a reader connects to the phone. We assume that
/// The reader handles RSSi calculations
- (TriggerResult * _Nonnull)readerConnectedTriggerWithReader:(MobileKeysReader * _Nonnull)reader SWIFT_WARN_UNUSED_RESULT;
- (TriggerResult * _Nonnull)userActionClosestReaderWithType:(MobileKeysOpeningType)type SWIFT_WARN_UNUSED_RESULT;
- (TriggerResult * _Nonnull)specificReaderWithReader:(MobileKeysReader * _Nonnull)reader type:(MobileKeysOpeningType)type SWIFT_WARN_UNUSED_RESULT;
- (void)setSupportedOpeningTypesWithTypes:(NSArray<NSNumber *> * _Nonnull)types;
- (BOOL)supportsOpeningTypeWithType:(MobileKeysOpeningType)type SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ReaderModuleType, open) {
  ReaderModuleTypeBleScanner = 0,
  ReaderModuleTypeBleAdvertiser = 1,
};


SWIFT_CLASS("_TtC17SeosMobileKeysSDK16ReaderRepository")
@interface ReaderRepository : NSObject
- (MobileKeysReader * _Nullable)closestReader SWIFT_WARN_UNUSED_RESULT;
- (MobileKeysReader * _Nullable)closestActivePeripheralForOpeningTypeWithType:(MobileKeysOpeningType)type SWIFT_WARN_UNUSED_RESULT;
- (MobileKeysReader * _Nullable)closestPeripheralForOpeningTypeWithType:(MobileKeysOpeningType)type enforceTimeout:(BOOL)enforceTimeout SWIFT_WARN_UNUSED_RESULT;
- (void)addRssiWithReader:(MobileKeysReader * _Nonnull)reader rssi:(NSInteger)rssi;
- (void)updateOrSaveWithReader:(MobileKeysReader * _Nonnull)reader;
- (MobileKeysReader * _Nullable)findReaderWithUuid:(NSString * _Nonnull)uuid SWIFT_WARN_UNUSED_RESULT;
- (void)removeReaderWithUuid:(NSString * _Nonnull)uuid;
- (NSArray<MobileKeysReader *> * _Nonnull)listAllActiveReaders SWIFT_WARN_UNUSED_RESULT;
- (void)removeInactiveReadersWithCallback:(void (^ _Nonnull)(MobileKeysReader * _Nonnull))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SecureChannelOperation, open) {
  SecureChannelOperationENCRYPT = 0,
  SecureChannelOperationDECRYPT = 1,
  SecureChannelOperationGET_PUBLIC_KEYS = 2,
  SecureChannelOperationCLOSE = 3,
};


/// Applications should conform to this protocol in order to handle data received from the connected device
/// through the secure channel after it has been decrypted.
SWIFT_PROTOCOL("_TtP17SeosMobileKeysSDK21SecureChannelReceiver_")
@protocol SecureChannelReceiver
/// This method will be invoked by the SDK after encrypted data has been received from the connected
/// device and decrypted by Seos.
/// @param data - Plaintext read by the connected device and decrypted by Seos.
- (void)didReceiveFromChannel:(NSData * _Nonnull)data;
@end


SWIFT_PROTOCOL("_TtP17SeosMobileKeysSDK19SecureChannelSender_")
@protocol SecureChannelSender
- (void)sendFromChannel:(NSData * _Nonnull)data;
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK15SeosApduCommand")
@interface SeosApduCommand : NSObject
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isManageChannel SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nonnull)toData SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK16Seos2ApduCommand")
@interface Seos2ApduCommand : SeosApduCommand
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData OBJC_DESIGNATED_INITIALIZER;
@end



/// <ul>
///   <li>
///     Create a get data command
///   </li>
///   <li>
///     @param tag The data tag
///   </li>
///   <li>
///     @param supportsSecureMessaging SecureMessaging enabled
///   </li>
///   <li>
///     @see “Section 9.8 in the Seos Core Technology Specification”
///   </li>
/// </ul>
SWIFT_CLASS("_TtC17SeosMobileKeysSDK22SeosApduCommandGetData")
@interface SeosApduCommandGetData : SeosApduCommand
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK36SeosApduCommandGetEndpointParameters")
@interface SeosApduCommandGetEndpointParameters : SeosApduCommandGetData
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK40SeosApduCommandGetLastAuthenticationInfo")
@interface SeosApduCommandGetLastAuthenticationInfo : SeosApduCommandGetData
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK32SeosApduCommandGetServerMetadata")
@interface SeosApduCommandGetServerMetadata : SeosApduCommandGetData
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK23SeosApduCommandListAdfs")
@interface SeosApduCommandListAdfs : SeosApduCommand
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData OBJC_DESIGNATED_INITIALIZER;
@end



/// <ul>
///   <li>
///     Create a put data command
///   </li>
///   <li>
///   </li>
///   <li>
///     @return The put data command
///   </li>
///   <li>
///     @see “Section 9.9 in the Seos Core Technology Specification”
///   </li>
/// </ul>
SWIFT_CLASS("_TtC17SeosMobileKeysSDK22SeosApduCommandPutData")
@interface SeosApduCommandPutData : SeosApduCommand
- (nonnull instancetype)initWithRawData:(NSData * _Nonnull)rawData SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK23SeosApduCommandSequence")
@interface SeosApduCommandSequence : NSObject
- (nonnull instancetype)initWithCommands:(NSArray<SeosApduCommand *> * _Nonnull)commands OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// <ul>
///   <li>
///     Interface for sending APDU commands to, and receiving APDU responses from a Seos card.
///   </li>
///   <li>
///     How implementations of this interface would look depends on where the API is used,
///   </li>
///   <li>
///     for instance the local file system, Bluetooth, NFC, USB or WIFI, etc.
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP17SeosMobileKeysSDK26SeosApduConnectionProtocol_")
@protocol SeosApduConnectionProtocol
/// <ul>
///   <li>
///     To check if there is already an ongoing connection using this ApduConnection
///   </li>
///   <li>
///     @return YES if there is an already open connection
///   </li>
/// </ul>
- (BOOL)activeConnection SWIFT_WARN_UNUSED_RESULT;
/// For APDUConnections that require special setup before apdu processing is initiated, you can implement this
/// protocol method to do such processing.
/// Examples of this could be that the APDU Connetion could connect to an external Seos Implementation, or load state
/// from file, or anything that needs to be performed before the Seos Implementation is ready to start accepting
/// APDU Commands.
/// @param options A NSDictionary of implementation specific options.
/// @param contactLess = YES if the session is made over the contactless inteface
/// @param error if something went wrong this parameter is set, otherwise nil.
/// @return YES if everything went OK.
- (BOOL)preSessionSetupWithOptions:(NSDictionary * _Nullable)options contactless:(BOOL)contactLess error:(NSError * _Nullable * _Nullable)error;
/// <ul>
///   <li>
///     For APDUConnections that require special processing when the session has been closed, you can implement this optional
///   </li>
///   <li>
///     protocol method to do such processing. Examples of this could be tearing down TCP sessions, encrypting and storing state etc.
///   </li>
///   <li>
///     @param options A NSDictionary of implementation specific options.
///   </li>
///   <li>
///     @param error if something went wrong, otherwise nil.
///   </li>
///   <li>
///     @return YES if everything went OK
///   </li>
/// </ul>
- (BOOL)postSessionTearDownWithOptions:(NSDictionary * _Nullable)options error:(NSError * _Nullable * _Nullable)error;
/// <ul>
///   <li>
///     Sends an APDU command and receives a response from the Seos applet. This is a raw APDU processing interface.
///   </li>
///   <li>
///     @param data The data command to send.
///   </li>
///   <li>
///     @param completion The result from Seos processing the command.
///   </li>
/// </ul>
- (void)processApdu:(NSData * _Nonnull)data completion:(void (^ _Nonnull)(NSData * _Nonnull))completion;
/// <ul>
///   <li>
///     Indicate to the Apdu Connection protocol that it should use test vectors.
///   </li>
///   <li>
///     @param enableTestVectors True or false
///   </li>
/// </ul>
- (void)enableTestVectors:(BOOL)enableTestVectors;
/// A secure channel that can decrypt and encrypt data. This is a raw processing interface.
/// @param data The data command to encrypt/decrypt.
/// @param operation The operation can be decrypt, encrypt, close and GetPublicKeys.
/// @return The result from the channel
- (NSData * _Nullable)processChannelWithData:(NSData * _Nonnull)data operation:(enum SecureChannelOperation)operation error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Check if the connection is open and in bidirectional mode.
/// @return YES if connection is open and in bidirectional mode
- (BOOL)isBidirectional SWIFT_WARN_UNUSED_RESULT;
@end

@class SeosStatusWord;

SWIFT_CLASS("_TtC17SeosMobileKeysSDK16SeosApduResponse")
@interface SeosApduResponse : NSObject
@property (nonatomic, copy) NSData * _Nullable payload;
@property (nonatomic, strong) SeosStatusWord * _Nonnull statusWord;
- (nullable instancetype)initWithRawData:(NSData * _Nonnull)rawData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data statusWord:(SeosStatusWord * _Nonnull)statusWord OBJC_DESIGNATED_INITIALIZER;
- (NSData * _Nonnull)toData SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK24SeosApduResponseSequence")
@interface SeosApduResponseSequence : NSObject
@property (nonatomic, copy) NSArray<SeosApduResponse *> * _Nonnull responses;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResponses:(NSArray<SeosApduResponse *> * _Nonnull)responses OBJC_DESIGNATED_INITIALIZER;
- (void)addApduResponse:(SeosApduResponse * _Nullable)response;
- (BOOL)isComplete SWIFT_WARN_UNUSED_RESULT;
- (NSArray<SeosApduResponse *> * _Nonnull)getResponses SWIFT_WARN_UNUSED_RESULT;
@end

enum SeosKeyNumber : uint8_t;
@class SeosSymmetricKeyPair;
enum SeosEncryptionAlgorithm : uint8_t;
@class SeosSelectionResult;

/// Interface for authentication credentials used during mutual authentication with Seos
SWIFT_CLASS("_TtC17SeosMobileKeysSDK24SeosAuthenticationKeySet")
@interface SeosAuthenticationKeySet : NSObject
/// Initialize
/// @param keyNumber             the key number for this credential.
/// @param symmetricKeyPair      the key pair to use for encryption and MAC calculations during authentication.
/// @param encryptionAlgorithm   the encryption algorithm to use during authentication
/// @param global                yes if this key references a global key
- (nonnull instancetype)initWithKeyNumber:(enum SeosKeyNumber)keyNumber symmetricKeyPair:(SeosSymmetricKeyPair * _Nullable)symmetricKeyPair encryptionAlgorithm:(enum SeosEncryptionAlgorithm)encryptionAlgorithm global:(BOOL)global OBJC_DESIGNATED_INITIALIZER;
/// Initialize
/// @param keyNumber             the key number for this credential.
/// @param symmetricKeyPair      the key pair to use for encryption and MAC calculations during authentication.
/// @param encryptionAlgorithm   the encryption algorithm to use during authentication
/// @param global                yes if this key references a global key
- (nonnull instancetype)initWithKeyNumber:(enum SeosKeyNumber)keyNumber certificateType:(enum CertificateType)certificateType encryptionAlgorithm:(enum SeosEncryptionAlgorithm)encryptionAlgorithm global:(BOOL)global OBJC_DESIGNATED_INITIALIZER;
/// Get the <code>SeosSymmetricKeyPair</code> used for encryption and MAC calculations during authentication.
/// @return the key pair used for encryption and MAC calculation.
- (SeosSymmetricKeyPair * _Nullable)authenticationKeysWithSelectionResultWithResult:(SeosSelectionResult * _Nullable)result SWIFT_WARN_UNUSED_RESULT;
/// Get the key number used for authentication.
/// @return the keynumber.
- (enum SeosKeyNumber)keyRef SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Encryption algorithms used by Seos
typedef SWIFT_ENUM(uint8_t, SeosEncryptionAlgorithm, open) {
  SeosEncryptionAlgorithmENCRYPTION_ALGO_ERROR = 0x00,
  SeosEncryptionAlgorithmENCRYPTION_ALGO_AES_128 = 0x09,
  SeosEncryptionAlgorithmENCRYPTION_ALGO_ECC_SECP256R1 = 0x11,
};

/// Hash algorithms used by Seos
typedef SWIFT_ENUM(uint8_t, SeosHashAlgorithm, open) {
  SeosHashAlgorithmHASH_ALGO_ERROR = 0x00,
  SeosHashAlgorithmHASH_ALGO_HMAC_SHA_256 = 0x07,
  SeosHashAlgorithmHASH_ALGO_CMAC_AES = 0x09,
};

typedef SWIFT_ENUM(uint8_t, SeosKeyNumber, open) {
  SeosKeyNumberKEY_0 = 0,
  SeosKeyNumberKEY_1 = 1,
  SeosKeyNumberKEY_2 = 2,
  SeosKeyNumberKEY_3 = 3,
  SeosKeyNumberKEY_4 = 4,
  SeosKeyNumberKEY_5 = 5,
  SeosKeyNumberKEY_6 = 6,
  SeosKeyNumberKEY_7 = 7,
  SeosKeyNumberKEY_8 = 8,
  SeosKeyNumberKEY_9 = 9,
  SeosKeyNumberKEY_10 = 10,
  SeosKeyNumberKEY_11 = 11,
  SeosKeyNumberKEY_12 = 12,
  SeosKeyNumberKEY_13 = 13,
  SeosKeyNumberKEY_14 = 14,
  SeosKeyNumberKEY_15 = 15,
  SeosKeyNumberKEY_16 = 16,
  SeosKeyNumberKEY_17 = 17,
  SeosKeyNumberKEY_18 = 18,
  SeosKeyNumberKEY_19 = 19,
  SeosKeyNumberKEY_20 = 20,
  SeosKeyNumberKEY_21 = 21,
  SeosKeyNumberKEY_22 = 22,
  SeosKeyNumberKEY_23 = 23,
  SeosKeyNumberKEY_24 = 24,
  SeosKeyNumberKEY_25 = 25,
  SeosKeyNumberKEY_26 = 26,
  SeosKeyNumberKEY_27 = 27,
  SeosKeyNumberKEY_28 = 28,
  SeosKeyNumberKEY_29 = 29,
  SeosKeyNumberKEY_30 = 30,
  SeosKeyNumberKEY_31 = 31,
  SeosKeyNumberKEY_FF = 0xff,
};

@class SeosProvider;
@class MobileKeysEndpointInfo;
@class MobileKeysKey;
@class MobileKeysLastAuthenticationInfo;
@class SeosTag;
@class NSNumber;

SWIFT_CLASS("_TtC17SeosMobileKeysSDK11SeosManager")
@interface SeosManager : NSObject
- (nonnull instancetype)initWithProvider:(SeosProvider * _Nonnull)provider OBJC_DESIGNATED_INITIALIZER;
- (BOOL)seosFileSystemExists SWIFT_WARN_UNUSED_RESULT;
- (BOOL)validateVault SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEndpointSetup SWIFT_WARN_UNUSED_RESULT;
- (MobileKeysEndpointInfo * _Nullable)endpointInfoAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)readbackIsApplicable SWIFT_WARN_UNUSED_RESULT;
- (NSArray<MobileKeysKey *> * _Nullable)listMobileKeysAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (MobileKeysLastAuthenticationInfo * _Nullable)lastAuthenticationInfoAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)getDataWithOid:(NSString * _Nonnull)oid tag:(SeosTag * _Nonnull)tag error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)putDataWithData:(NSData * _Nonnull)data oid:(NSString * _Nonnull)oid tag:(SeosTag * _Nonnull)tag error:(NSError * _Nullable * _Nullable)error;
- (BOOL)toggleMobileKeyWithKey:(MobileKeysKey * _Nonnull)key enable:(BOOL)enable SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)generateOTPForKeyWithKey:(MobileKeysKey * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSNumber * _Nullable)otpCounterForKeyWithKey:(MobileKeysKey * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a master authentication credential, used to calculate derived keys based on diversification data.
/// @see “Section 2.1 in the Seos Core Technology Specification”
SWIFT_CLASS("_TtC17SeosMobileKeysSDK30SeosMasterAuthenticationKeySet")
@interface SeosMasterAuthenticationKeySet : SeosAuthenticationKeySet
/// Constructs a master key credential.
/// @param keyNumber     the key number this key should authenticate to.
/// @param masterKey      the master key data, 16 bytes AES key used to derive card specific keys.
/// @param oid                   oid to use during key derivation, selected Oid used if null
/// @param diversifier        diversifier to use during key derivation, selected ADF Diversifier used if null
/// @param global              true of the referred key is global, false if the key number refers to a ADF local key.
- (nonnull instancetype)initWithKeyNumer:(enum SeosKeyNumber)keyNumer masterKey:(NSData * _Nonnull)masterKey oid:(NSData * _Nullable)oid diversifier:(NSData * _Nullable)diversifier encryptionAlgorithm:(enum SeosEncryptionAlgorithm)encryptionAlgorithm global:(BOOL)global OBJC_DESIGNATED_INITIALIZER;
/// Get the <code>SeosSymmetricKeyPair</code> used for encryption and MAC calculations during authentication.
/// @param result Information about selected OID and it’s diversifier.
/// @return the key pair used for encryption and MAC calculation.
- (SeosSymmetricKeyPair * _Nullable)authenticationKeysWithSelectionResultWithResult:(SeosSelectionResult * _Nullable)result SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithKeyNumber:(enum SeosKeyNumber)keyNumber symmetricKeyPair:(SeosSymmetricKeyPair * _Nullable)symmetricKeyPair encryptionAlgorithm:(enum SeosEncryptionAlgorithm)encryptionAlgorithm global:(BOOL)global SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithKeyNumber:(enum SeosKeyNumber)keyNumber certificateType:(enum CertificateType)certificateType encryptionAlgorithm:(enum SeosEncryptionAlgorithm)encryptionAlgorithm global:(BOOL)global SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK19SeosNativeInterface")
@interface SeosNativeInterface : NSObject <SeosApduConnectionProtocol>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)activeConnection SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isBidirectional SWIFT_WARN_UNUSED_RESULT;
- (BOOL)preSessionSetupWithOptions:(NSDictionary * _Nullable)options contactless:(BOOL)contactLess error:(NSError * _Nullable * _Nullable)error;
- (BOOL)postSessionTearDownWithOptions:(NSDictionary * _Nullable)options error:(NSError * _Nullable * _Nullable)error;
- (void)processApdu:(NSData * _Nonnull)data completion:(SWIFT_NOESCAPE void (^ _Nonnull)(NSData * _Nonnull))completion;
- (void)enableTestVectors:(BOOL)enableTestVectors;
- (void)updateVirtualDataWithVirtualData:(NSData * _Nonnull)virtualData;
- (void)updateCustomAttributeFieldWithData:(NSData * _Nonnull)data;
- (NSData * _Nullable)processChannelWithData:(NSData * _Nonnull)data operation:(enum SecureChannelOperation)operation error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


/// Privacy keyset to use during Seos session establishment.
SWIFT_CLASS("_TtC17SeosMobileKeysSDK17SeosPrivacyKeySet")
@interface SeosPrivacyKeySet : NSObject
/// Creates an instance of a SeosPrivacyKeySet object
/// @param keyNumber             the key number for this credential
/// @param symmetricKeyPair      the symmetric key pair to use for encryption in this session
/// @param encryptionAlgorithm   The encryption algorithm to use
- (nonnull instancetype)initWithKeyNumber:(enum SeosKeyNumber)keyNumber symmetricKeyPair:(SeosSymmetricKeyPair * _Nonnull)symmetricKeyPair encryptionAlgorithm:(enum SeosEncryptionAlgorithm)encryptionAlgorithm usesPrivacy:(BOOL)usesPrivacy OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SeosSessionParameters;
@protocol SeosSessionProtocol;
@class SeosSession;

SWIFT_PROTOCOL("_TtP17SeosMobileKeysSDK20SeosProviderProtocol_")
@protocol SeosProviderProtocol
- (BOOL)establishSessionWithSessionParameters:(SeosSessionParameters * _Nonnull)sessionParameters description:(NSString * _Nullable)description error:(NSError * _Nullable * _Nullable)error completion:(void (^ _Nonnull)(id <SeosSessionProtocol> _Nonnull))completion;
- (id <SeosSessionProtocol> _Nullable)establishSessionWithSessionParameters:(SeosSessionParameters * _Nonnull)sessionParameters description:(NSString * _Nullable)description error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <SeosSessionProtocol> _Nullable)establishCardSessionUsingTerminalSession:(SeosSession * _Nonnull)terminalSession cardParameters:(SeosSessionParameters * _Nonnull)cardParameters terminalParameters:(SeosSessionParameters * _Nonnull)terminalParameters error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isOpen SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isBidirectional SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)currentSessionClient SWIFT_WARN_UNUSED_RESULT;
@end


/// This SeosProvider is the interface to access a Seos instance.
/// @warning Due to the single threaded nature of Seos, only one session can be opened at once.
SWIFT_CLASS("_TtC17SeosMobileKeysSDK12SeosProvider")
@interface SeosProvider : NSObject <SeosProviderProtocol>
/// Constructs a <code>SeosProvider</code> using the selected <code>SeosApduConnectionProtocol</code>
/// @param apduConnection      the APDU connection to use in this instance
/// @return                                  an instance of <code>SeosProvider</code>
- (nonnull instancetype)initWithConnection:(id <SeosApduConnectionProtocol> _Nonnull)connection OBJC_DESIGNATED_INITIALIZER;
/// Establish a session to the Apdu Connection. This method will make sure that only one session is open at a time. The specific
/// session opening mechanics will be specified by the SeosSessionParameters object. Depending on the parameters, this
/// function will perform some or all of the following functions:
/// <ul>
///   <li>
///     Create a session
///   </li>
///   <li>
///     Select the Seos AID
///   </li>
///   <li>
///     Select a specific ADF or GDF using provided parameters
///   </li>
///   <li>
///     Perform Mutual Authentication to Seos and set up Encryption parameters
///   </li>
/// </ul>
/// @param sessionParameters     the parameters provided for this session. See SeosSessionParameters for a specification
/// @param description                   A free-text description (primarily used when debugging, but required notheless)
/// @throws                                     if the session failed to open. The error will contain a code, see SeosErrorCode for a description
/// @completion                              a SeosSession object.
- (BOOL)establishSessionWithSessionParameters:(SeosSessionParameters * _Nonnull)sessionParameters description:(NSString * _Nullable)description error:(NSError * _Nullable * _Nullable)error completion:(void (^ _Nonnull)(id <SeosSessionProtocol> _Nonnull))completion;
- (id <SeosSessionProtocol> _Nullable)establishSessionWithSessionParameters:(SeosSessionParameters * _Nonnull)sessionParameters description:(NSString * _Nullable)description error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <SeosSessionProtocol> _Nullable)establishCardSessionUsingTerminalSession:(SeosSession * _Nonnull)terminalSession cardParameters:(SeosSessionParameters * _Nonnull)cardParameters terminalParameters:(SeosSessionParameters * _Nonnull)terminalParameters error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Check if a session is currently open. This will call the “activeConnection” method of the current session, if one is available.
///   </li>
///   <li>
///     @return YES if session is open.
///   </li>
/// </ul>
- (BOOL)isOpen SWIFT_WARN_UNUSED_RESULT;
/// Check if a session is currently open and in bidirectional mode.
/// @return YES if session is open and in bidirectional mode
- (BOOL)isBidirectional SWIFT_WARN_UNUSED_RESULT;
/// If a session is currently open this method will return the current client.
/// If there is no session open this method will return an empty string.
/// @return the current client of the Seos provider if there is one.
- (NSString * _Nullable)currentSessionClient SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




/// A bi-directional communication channel that a device can open up with an endpoint. Data sent through
/// this channel will be encrypted by Seos.
SWIFT_CLASS("_TtC17SeosMobileKeysSDK17SeosSecureChannel")
@interface SeosSecureChannel : NSObject
@property (nonatomic, readonly) BOOL isOpen;
@property (nonatomic, strong) id <SecureChannelReceiver> _Nullable receiver;
@property (nonatomic, readonly, copy) NSData * _Nullable publicKeys;
- (nonnull instancetype)initWithSender:(id <SecureChannelSender> _Nonnull)sender seosSession:(SeosSession * _Nonnull)seosSession OBJC_DESIGNATED_INITIALIZER;
- (void)close;
- (BOOL)writeToChannel:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
- (BOOL)didReceiveIntoChannel:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Describes the result of ADF/GDF selection.
SWIFT_CLASS("_TtC17SeosMobileKeysSDK19SeosSelectionResult")
@interface SeosSelectionResult : NSObject
/// Get the hash algorithm used by the selected ADF/GDF.
/// @return the hash algorithm used by the selected ADF/GDF.
@property (nonatomic) enum SeosHashAlgorithm hashAlgorithm;
/// Get the encryption algorithm used by the selected ADF/GDF.
/// @return the encryption algorithm used by the selected ADF/GDF.
@property (nonatomic) enum SeosEncryptionAlgorithm encAlgorithm;
/// Get the OID of the selected ADF/GDF.
/// @return the OID of the selected ADF/GDF.
@property (nonatomic, copy) NSData * _Nonnull selectedOid;
/// Get the diversifier used by the selected ADF/GDF.
/// @return the diversifier used by the selected ADF/GDF.
@property (nonatomic, copy) NSData * _Nonnull diversifier;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Describes the type of ADF selection to use during session establishment.
typedef SWIFT_ENUM(NSInteger, SeosSelectionType, open) {
  SeosSelectionTypeAdf = 0,
  SeosSelectionTypeGdf = 1,
  SeosSelectionTypeExtendedADF = 2,
  SeosSelectionTypeEmptySeos = 3,
  SeosSelectionTypeNone = 4,
};


SWIFT_PROTOCOL("_TtP17SeosMobileKeysSDK19SeosSessionProtocol_")
@protocol SeosSessionProtocol
@property (nonatomic, copy) NSDictionary * _Nullable postSessionTearDownOptions;
- (void)processApduCommand:(SeosApduCommand * _Nonnull)command completion:(void (^ _Nonnull)(SeosApduResponse * _Nonnull))completion;
- (SeosApduResponse * _Nullable)processApduCommand:(SeosApduCommand * _Nonnull)command error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (SeosApduResponseSequence * _Nullable)processApduCommandSequence:(SeosApduCommandSequence * _Nonnull)sequence error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)closeSession SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)processChannel:(NSData * _Nonnull)data with:(enum SecureChannelOperation)operation error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)activeConnection SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isBidirectional SWIFT_WARN_UNUSED_RESULT;
@end


/// SeosSession implements seos apdu connection protocol to get access to a seos core.
/// The Seos session is used to send apdu commands and recive apdu responses from the core.
SWIFT_CLASS("_TtC17SeosMobileKeysSDK11SeosSession")
@interface SeosSession : NSObject <SeosSessionProtocol>
/// The Seos session can have post session options that can be executed
@property (nonatomic, copy) NSDictionary * _Nullable postSessionTearDownOptions;
/// Constructs a <code>SeosSession</code> with the specified <code>SeosApduConnectionProtocol</code>
/// @param apduConnection      The APDU connection to use in this session
/// @return                                  A session instance
- (nonnull instancetype)initWithApduConnection:(id <SeosApduConnectionProtocol> _Nonnull)apduConnection OBJC_DESIGNATED_INITIALIZER;
/// Sends an APDU command and receives a response from the Seos applet.
/// @param command    The apdu command to send.
/// @return                      The response from Seos processing the command
- (void)processApduCommand:(SeosApduCommand * _Nonnull)command completion:(void (^ _Nonnull)(SeosApduResponse * _Nonnull))completion;
- (SeosApduResponse * _Nullable)processApduCommand:(SeosApduCommand * _Nonnull)command error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (SeosApduResponseSequence * _Nullable)processApduCommandSequence:(SeosApduCommandSequence * _Nonnull)sequence error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Close seos session
/// @return YES if seos session was closed without errors
- (BOOL)closeSession;
/// <ul>
///   <li>
///     A secure channel that can decrypt and encrypt data. This is a raw processing interface.
///   </li>
///   <li>
///   </li>
///   <li>
///     @param data          The data to encrypt/decrypt.
///   </li>
///   <li>
///     @param operation  The operation can be decrypt, encrypt, close and GetPublicKeys.
///   </li>
///   <li>
///     @return                   The result from the channel
///   </li>
/// </ul>
- (NSData * _Nullable)processChannel:(NSData * _Nonnull)data with:(enum SecureChannelOperation)operation error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Check if a session is currently open. This will call the “activeConnection” method of the current session, if one is available.
///   </li>
///   <li>
///     @return YES if session is open.
///   </li>
/// </ul>
- (BOOL)activeConnection SWIFT_WARN_UNUSED_RESULT;
/// Check if a session is currently open and in bidirectional mode.
/// @return YES if session is open and in bidirectional mode
- (BOOL)isBidirectional SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SeosSessionClientIdentifier, open) {
  SeosSessionClientIdentifierUnspecified = 0,
  SeosSessionClientIdentifierBle = 1,
  SeosSessionClientIdentifierTsm = 2,
  SeosSessionClientIdentifierReadback = 3,
  SeosSessionClientIdentifierInternalSeos = 4,
  SeosSessionClientIdentifierThirdParty = 5,
};


SWIFT_CLASS("_TtC17SeosMobileKeysSDK21SeosSessionParameters")
@interface SeosSessionParameters : NSObject
/// The type of selection that the SeosProvider#openSessionWithParams:withError: should perform.
/// <ul>
///   <li>
///     adf : Select an ADF
///   </li>
///   <li>
///     gdf : Select the GDF
///   </li>
///   <li>
///     extendedADF : Administration
///   </li>
///   <li>
///     emptySeos : empty selection
///   </li>
///   <li>
///     none : do not perform an initial select
///   </li>
/// </ul>
@property (nonatomic) enum SeosSelectionType selectionType;
/// Open Sessions can be classified by the client identifier.
/// <ul>
///   <li>
///     unspecified : Select an ADF
///   </li>
///   <li>
///     ble : Internally used by the Mobile Access SDK. Don’t use.
///   </li>
///   <li>
///     tsm : Internally used by the Mobile Access SDK. Don’t use.
///   </li>
///   <li>
///     thirdParty : Third party integrators should use this.
///   </li>
/// </ul>
@property (nonatomic) enum SeosSessionClientIdentifier sessionClientIdentifier;
/// This is privacy keyset used when selecting the ADF or GDF.
@property (nonatomic, strong) SeosPrivacyKeySet * _Nullable privacyKeySet;
/// This is the authentication keyset used for mutual authentication when setting up a session with Seos.
/// Set this to nil if no mutual authentication should be performed.
/// @see {@link SeosAuthenticationKeyset}
/// @see {@link SeosMasterAuthenticationKeyset}
@property (nonatomic, strong) SeosAuthenticationKeySet * _Nullable authenticationKeySet;
/// If the Seos implementation supports it, this parameter will define whether or not the communication will be
/// performed over the contactless or the contact interface.
@property (nonatomic) BOOL contactless;
/// If this property is set to YES, the SDK will gladly accept payload larger than 255 bytes, and will automatically split
/// these APDUs into multiple commands. Normally, this can be used to PUT data larger than 255 bytes to a tag.
/// Defaults to NO
@property (nonatomic) BOOL autoSplitLargeApduCommands;
/// If the property is set to YES, the SDK will automatically request the next response if a ApduResponse indicates that
/// there is more data to read. Normally, this can be used to GET data from a tag where the data is larger than 255 bytes.
/// Defaults to NO.
@property (nonatomic) BOOL autoJoinMultipleApduResponses;
/// If this parameter is set to YES, the session will initially select the Seos application by it’s AID.
/// Default value is YES.
@property (nonatomic) BOOL requireSelectAid;
/// If this parameter is YES, the mutual authentication to Seos will be performed using hard-coded test vectors
/// according to the Seos Specification.
@property (nonatomic) BOOL useTestVectors;
/// A list of OIDs that will be used when selecting the ADF or the GDF. It is possible to pass multiple OIDs,
/// and Seos will try to select them in the order in which they are specified. Only one OID will be selected however,
/// and the OID of the successfully selected file will be returned by the SeosProvider#openSessionWithParams:withError:
/// method
/// Seos supports partial selects, and keep in mind that if multiple keys match a partial OID selection, the first found key
/// (undefined order) will be selected.
@property (nonatomic, copy) NSArray<NSData *> * _Nullable oidSelectionList;
/// A timeout when acquiring a seos session, since Seos can only handle one session at time. Defaults to “0” meaning that session opening fails immediately if Seos is busy.
/// If this is set to a positive number larger than zero, the thread will lock and wait for the specified amount waiting for a Seos session to become
/// available. If no session can be opened within timeout seconds, the session opening will fail.
/// The timeout needs to be specified in miliseconds.
@property (nonatomic) NSInteger timeoutInMilliSeconds;
/// Constructs a <code>SeosSessionParameters</code> using the selected parameters
/// @param selectionType             the type of Selection to be performed. Specifies the type of select (ADF or GDF) to use in the session
/// @param privacyKeySet             the privacy credential to use to protect privacy during ADF/GDF selection
/// @param authenticationKeySet    authentication credential to use during mutual authentication. If no authentication key is specified, no mutual authentication will be performed during session establishment.
/// @return                                  an instance of <code>SeosSessionParameters</code>
- (nonnull instancetype)initWithSelectionType:(enum SeosSelectionType)selectionType privacyKeySet:(SeosPrivacyKeySet * _Nullable)privacyKeySet authenticationKeySet:(SeosAuthenticationKeySet * _Nullable)authenticationKeySet oidSelectionList:(NSArray<NSData *> * _Nullable)oidSelectionList OBJC_DESIGNATED_INITIALIZER;
/// Factory method to create parameters for contactless sessions with no security.
/// @param shouldSelectAid If the Session should do an AID select when setting up
/// @param contactless if this is contactless session
/// @return a predefined session parameters object with the specified parameters
+ (nonnull instancetype)parametersForNoSecurityWithSelectAidWithShouldSelectAid:(BOOL)shouldSelectAid contacless:(BOOL)contacless SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)parametersForBle SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)parametersForTsm SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)parametersForCache SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)parametersForReadback SWIFT_WARN_UNUSED_RESULT;
- (BOOL)requiresSecureMessaging SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC17SeosMobileKeysSDK14SeosStatusWord")
@interface SeosStatusWord : NSObject
- (nonnull instancetype)initWithUpperByte:(uint8_t)upperByte lowerByte:(uint8_t)lowerByte OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithWord:(uint16_t)word;
- (NSData * _Nonnull)toData SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isOk SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Interface for symmetric keys used in Seos authentication and privacy cryptography.
SWIFT_CLASS("_TtC17SeosMobileKeysSDK20SeosSymmetricKeyPair")
@interface SeosSymmetricKeyPair : NSObject
/// Constructs a <code>SeosSymmetricKeyPair</code> using the specified encryption and mac key
/// @param macKey    the mac key value
/// @param encKey    the encryption key value
/// @param encAlg    the encryption algorithm of the <code>encKey</code>
/// @return          an instance of <code>SeosSymmetricKeyPair</code>
- (nonnull instancetype)initWithMacKey:(NSData * _Nonnull)macKey encKey:(NSData * _Nonnull)encKey encAlg:(enum SeosEncryptionAlgorithm)encAlg OBJC_DESIGNATED_INITIALIZER;
/// Constructs a <code>SeosSymmetricKeyPair</code> using the specified encryption and mac key.
/// This is a convenience method for using <code>ENCRYPTION_ALGO_AES_128</code> as the encryption algorithm
/// @param encKey    the encryption key value
/// @param macKey    the mac key value
/// @return          an instance of <code>SeosSymmetricKeyPair</code>
- (nonnull instancetype)initWithEncKey:(NSData * _Nonnull)encKey macKey:(NSData * _Nonnull)macKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17SeosMobileKeysSDK7SeosTag")
@interface SeosTag : NSObject
- (nonnull instancetype)initWithBytes:(NSData * _Nonnull)bytes;
- (nonnull instancetype)initWithSingleByte:(uint8_t)singleByte;
- (nonnull instancetype)initWithFirstByte:(uint8_t)firstByte secondByte:(uint8_t)secondByte;
- (nonnull instancetype)initWithTwoBytes:(uint16_t)twoBytes;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SeosTag (SWIFT_EXTENSION(SeosMobileKeysSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, State, open) {
  StateIDLE = 0,
  StateTRYINGTOSTART = 1,
  StateSTARTED = 2,
  StateADVERTISING = 3,
  StateSCANNING = 4,
  StateCONNECTING = 5,
  StateCONNECTED = 6,
  StateSERVICE_DISCOVERY = 7,
  StateSERVICES_DISCOVERED = 8,
  StateCHARACTERISTIC_DISCOVERY = 9,
  StateCHARACTERISTICS_DISCOVERED = 10,
  StateDATA_TRANSFER = 11,
  StateEND_OF_TRANSACTION = 12,
  StateDISCONNECTING = 13,
  StateDISCONNECTED = 14,
};

enum TriggerStatus : NSInteger;

SWIFT_CLASS("_TtC17SeosMobileKeysSDK13TriggerResult")
@interface TriggerResult : NSObject
@property (nonatomic, strong) MobileKeysReader * _Nullable reader;
@property (nonatomic) MobileKeysOpeningType openingType;
@property (nonatomic) enum TriggerStatus status;
@property (nonatomic, readonly) BOOL success;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TriggerStatus, open) {
  TriggerStatusSuccess = 0,
  TriggerStatusUnsupportedOpeningType = 1,
  TriggerStatusNoReaderInRange = 2,
  TriggerStatusReaderInTimeout = 3,
  TriggerStatusReaderNotFound = 4,
  TriggerStatusReaderNotActive = 5,
  TriggerStatusNoAction = 6,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
